//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXAMENPARCIAL_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasajeros
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> NumViajes { get; set; }
    }
}
