//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXAMENPARCIAL_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viajes
    {
        public int idConsultas { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idmedico { get; set; }
        public string Paciente { get; set; }
        public Nullable<int> totalconsulta { get; set; }
    }
}
